spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/depart/v1/**
          filters:
            - AuthenticationFilter
        - id: Activities-Service
          uri: lb://Activities-Service
          predicates:
            - Path=/v1/user/**
          filters:
            - AuthenticationFilter

        - id: Security-Service
          uri: lb://Security-Service
          predicates:
            - Path=/api/auth/**

      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true



server:
  port: 8889



eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: info



