version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: deneme
      MYSQL_DATABASE: deneme
      MYSQL_USER: mysql-boun
      MYSQL_PASSWORD: root
    ports:
      - 3336:3306